language: php

sudo: required
dist: trusty

php:
  - 5.6
  - 7.0

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 7.1
      env: EXTRA_TESTS=functional

addons:
  chrome: stable
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

before_script:
  - bash travis-scripts/setup-php-fpm.sh
  - bash travis-scripts/setup-apache.sh
  - bash travis-scripts/setup-selenium.sh

script:
  - tests/check_php_parse_errors.sh
  - bash travis-scripts/install-prestashop.sh
  - cd tests && bash getcomposer.sh && php composer.phar install && php vendor/bin/phpunit -c .
  - cd $TRAVIS_BUILD_DIR && bash travis-scripts/run-functional-tests.sh

after_failure:
  - curl -L http://localhost/
  - sudo cat /var/log/apache2/other_vhosts_access.log
